// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app/app-header.vue')['default']
    AppVideoItem: typeof import('./src/components/app/app-video-item.vue')['default']
    HomeChannel: typeof import('./src/components/home/home-channel.vue')['default']
    HomeSwipe: typeof import('./src/components/home/home-swipe.vue')['default']
    HomeVideoList: typeof import('./src/components/home/home-video-list.vue')['default']
    ImgMain: typeof import('./src/components/Search/ImgMain.vue')['default']
    LoginHeader: typeof import('./src/components/login/Login-header.vue')['default']
    LoginMain: typeof import('./src/components/login/Login-Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTop: typeof import('./src/components/Search/SearchTop.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanField: typeof import('vant/es')['Field']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VideoBottom: typeof import('./src/components/video/video-bottom.vue')['default']
    VideoComment: typeof import('./src/components/video/video-comment.vue')['default']
    VideoInfo: typeof import('./src/components/video/video-info.vue')['default']
    VideoPlay: typeof import('./src/components/video/video-play.vue')['default']
    VideoRecommend: typeof import('./src/components/video/video-recommend.vue')['default']
  }
}
